# Generated by Django 4.1 on 2023-04-03 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_name', models.CharField(max_length=250)),
                ('leader_father_name', models.CharField(max_length=255)),
                ('leader_date_of_birth', models.DateField()),
                ('leader_email', models.EmailField(max_length=254)),
                ('leader_address', models.CharField(max_length=455)),
                ('leader_contact_number', models.CharField(max_length=255)),
                ('leader_emergency_contact_person', models.CharField(max_length=255)),
                ('leader_emergency_contact_number', models.CharField(max_length=25)),
                ('leader_photo', models.FileField(upload_to='photos/')),
                ('leader_id_adhaar', models.FileField(upload_to='id_adhaar/')),
                ('leader_id_PCC', models.FileField(upload_to='id_pcc/')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('emergency_contact_person', models.CharField(max_length=255)),
                ('emergency_contact_number', models.CharField(max_length=20)),
                ('photo', models.FileField(upload_to='photos/')),
                ('id_proof', models.FileField(upload_to='id_proofs/')),
                ('id_proof_again', models.FileField(upload_to='id_proofs/')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='applicantform.team')),
            ],
        ),
    ]
