# Generated by Django 4.1 on 2023-04-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicantform', '0002_team_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
    ]
