# Generated by Django 4.1 on 2023-04-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicantform', '0003_remove_team_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='first_choice',
            field=models.CharField(choices=[('Bubble Maker', 'Bubble Maker '), ('Seal Team', 'Seal Team'), ('Open Water Diver', 'Open Water Diver')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
