# Generated by Django 4.1 on 2023-04-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicantform', '0004_team_first_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='first_choice',
            field=models.CharField(choices=[('Bubble Maker', 'Bubble Maker '), ('Seal Team', 'Seal Team'), ('Open Water Diver', 'Open Water Diver'), ('Adventure Diver', 'Adventure Diver'), ('Advanced Open Water Diver', 'Advanced Open Water Diver'), ('EFR Primary & Secondary Care', 'EFR Primary & Secondary Care'), ('Rescue Diver', 'Rescue Diver'), ('Dive Master', 'Dive Master')], max_length=100),
        ),
    ]
