# Generated by Django 4.1 on 2023-04-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicantform', '0005_alter_team_first_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='padi_specialty',
            field=models.CharField(choices=[('Deep Diver', 'Deep Diver'), ('Digital Underwater Photography', 'Digital Underwater Photography'), ('Enriched Air Diver', 'Enriched Air Diver'), ('Night Diver', 'Night Diver'), ('Adaptive Support Diver', 'Adaptive Support Diver'), ('Adaptive Techniques', 'Adaptive Techniques'), ('DSMB Diver', 'DSMB Diver'), ('Emergency Oxygen Provider', 'Emergency Oxygen Provider'), ('Underwater Navigator', 'Underwater Navigator'), ('Wreck Diver', 'Wreck Diver'), ('Peak Performance Buoyancy', 'Peak Performance Buoyancy')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
