# Generated by Django 4.1 on 2023-04-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicantform', '0007_team_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='checkin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
