# Generated by Django 4.1 on 2023-04-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicantform', '0008_team_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='checkout',
            field=models.DateField(blank=True, null=True),
        ),
    ]
