# Generated by Django 4.1 on 2023-04-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicantform', '0009_team_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ac_or_nonac',
            field=models.CharField(choices=[('AC', 'AC'), ('Non-AC', 'Non-AC')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='number_of_rooms',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='veg_or_nonveg',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non-veg', 'Non-veg')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
