# Generated by Django 4.1 on 2023-04-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicantform', '0012_alter_team_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('open', 'open'), ('Confirm', 'Confirm'), ('Closed', 'Closed')], default='Processing', max_length=100),
        ),
    ]
