# Generated by Django 4.1 on 2023-04-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicantform', '0015_alter_team_leader_id_pcc_alter_team_leader_id_adhaar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='leader_id_PCC',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='id_pcc/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader_id_adhaar',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='id_adhaar/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader_photo',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='photos/'),
        ),
    ]
