# Generated by Django 4.1 on 2023-04-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicantform', '0016_alter_team_leader_id_pcc_alter_team_leader_id_adhaar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='permit',
            field=models.CharField(choices=[('Not applied', 'Not applied'), ('Applied', 'Applied'), ('Need to apply', 'Need to apply'), ('Document waiting', 'Document waiting'), ('Permit ready', 'Permit ready'), ('Expired', 'Expired'), ('Without permit', 'Without permit')], default='Not applied', max_length=100),
        ),
    ]
