# Generated by Django 4.1 on 2023-04-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicantform', '0017_team_permit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='permit',
            field=models.CharField(choices=[('Not applied', 'Not applied'), ('Applied', 'Applied'), ('Need to apply', 'Need to apply'), ('Document waiting', 'Document waiting'), ('Permit ready', 'Permit ready'), ('Expired', 'Expired'), ('Without permit', 'Without permit')], max_length=100),
        ),
    ]
