# Generated by Django 4.1 on 2023-04-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicantform', '0019_alter_team_permit'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='admi_checkin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='admin_checkout',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='admin_number_of_rooms',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='room_name',
            field=models.CharField(choices=[('Alma S', 'Alma S'), ('Royal Arabia', 'Royal Arabia'), ('Capital inn', 'Capital inn'), ('AL-BE', 'AL-BE'), ('Bismillah', 'Bismillah'), ('Sea Shell', 'Sea Shell'), ('White Peril', 'White Peril'), ('Popular', 'Popular'), ('Palalam ', 'Palalam '), ('Thangal S ', 'Thangal S'), ('Lakscub KVT', 'Lakscub KVT'), ('Lakscuba KVT', 'Lakscuba KVT'), ('Mana', 'Mana'), ('R Resort', 'R Resort'), ('Gol Resort', 'Gol Resort'), ('Agatti Resort', 'Agatti Resort')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
