# Generated by Django 4.1 on 2023-04-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicantform', '0020_team_admi_checkin_team_admin_checkout_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='admi_checkin',
            new_name='admin_checkin',
        ),
    ]
